management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      instance: local
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  propagators:
    - tracecontext
    - baggage
  logs:
    exporter: none
spring:
  application:
    name: customer-service
  cloud:
    stream:
      kafka:
        binder:
          defaultBrokerPort: 29092
      bindings:
        customerRegisterStream-in-0:
          group: customer-register
          destination: customer-register
          content-type: application/json
    function:
      definition: customerRegisterStream
logging:
  level:
    org:
      apache:
        kafka: ERROR