management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
spring:
  application:
    name: customer-service
  cloud:
    stream:
      kafka:
        binder:
          defaultBrokerPort: 29092
      bindings:
        customerRegisterStream-in-0:
          group: customer-register
          destination: customer-register
          content-type: application/json
    function:
      definition: customerRegisterStream