version: '3.8'

services:
  mongodb:
    image: mongo:5.0.26
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123
volumes:
  mongodb-volume: